spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres_sample
    username: postgres
    password: password
  jpa:
    properties:
      hibernate:
        format-sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        use_sql_comments: true
        default_batch_fetch_size: 500
    open-in-view: false
